#!/usr/bin/ansible-playbook --inventory=localhost,
#
# install.yml
---
- hosts: localhost
  connection: local
  force_handlers: true

  tasks:

    - name: Enable SELinux in enforcing mode
      ansible.posix.selinux:
        policy: targeted
        state: enforcing
      notify: Relabel filesystem

    - name: Configure Bash shell for root
      ansible.builtin.copy:
        src: bashrc-root
        dest: /root/.bashrc
        owner: root
        group: root
        mode: 0644

    - name: Configure Bash shell for future users
      ansible.builtin.copy:
        src: bashrc-user
        dest: /etc/skel/.bashrc
        owner: root
        group: root
        mode: 0644

    - name: Install Vim
      ansible.builtin.dnf:
        name: vim-enhanced
        state: present
        install_weak_deps: false

    - name: Configure Vim editor for root
      ansible.builtin.copy:
        src: vimrc
        dest: /root/.vimrc
        owner: root
        group: root
        mode: 0644

    - name: Configure Vim editor for future users
      ansible.builtin.copy:
        src: vimrc
        dest: /etc/skel/.vimrc
        owner: root
        group: root
        mode: 0644

    - name: Configure Rocky Linux BaseOS repository
      ansible.builtin.yum_repository:
        name: baseos
        file: rocky
        description: BaseOS
        baseurl: 
          - http://mirror.in2p3.fr/pub/linux/rocky/$releasever/BaseOS/$basearch/os/
          - http://dl.rockylinux.org/$contentdir/$releasever/BaseOS/$basearch/os/
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9
        enabled: true
        priority: 1

    - name: Configure Rocky Linux AppStream repository
      ansible.builtin.yum_repository:
        name: appstream
        file: rocky
        description: AppStream
        baseurl: 
          - http://mirror.in2p3.fr/pub/linux/rocky/$releasever/AppStream/$basearch/os/
          - http://dl.rockylinux.org/$contentdir/$releasever/AppStream/$basearch/os/
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9
        enabled: true
        priority: 1

    - name: Configure Rocky Linux CRB repository
      ansible.builtin.yum_repository:
        name: crb
        file: rocky
        description: CRB
        baseurl: 
          - http://mirror.in2p3.fr/pub/linux/rocky/$releasever/CRB/$basearch/os/
          - http://dl.rockylinux.org/$contentdir/$releasever/CRB/$basearch/os/
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9
        enabled: true
        priority: 1

    - name: Configure Rocky Linux Extras repository
      ansible.builtin.yum_repository:
        name: extras
        file: rocky-extras
        description: Extras
        baseurl: 
          - http://mirror.in2p3.fr/pub/linux/rocky/$releasever/extras/$basearch/os/
          - http://dl.rockylinux.org/$contentdir/$releasever/extras/$basearch/os/
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9
        enabled: true
        priority: 1

# Dépôts EPEL

# Dépôts ELRepo

# Dépôts RPMFusion

# Installer le groupe de paquets Base

# Installer quelques outils supplémentaires

# Installer X11 + polices de base

# Installer KDE de base

# Installer GDM pour KDE

# Installer une panoplie d'applications

  handlers:

    - name: Relabel filesystem
      ansible.builtin.file:
        path: /.autorelabel
        state: touch

...
