#!/usr/bin/ansible-playbook --inventory=localhost,
#
# install.yml
---
- hosts: localhost
  connection: local
  force_handlers: true

  tasks:

    - name: Configure Bash shell for root
      ansible.builtin.copy:
        src: bashrc-root
        dest: /root/.bashrc
        owner: root
        group: root
        mode: 0644

...
