#!/usr/bin/ansible-playbook --inventory=localhost,
#
# install.yml
---
- hosts: localhost
  connection: local
  force_handlers: true

  tasks:

    - name: Enable SELinux in enforcing mode
      ansible.posix.selinux:
        policy: targeted
        state: enforcing
      notify: Relabel filesystem

    - name: Configure Bash shell for root
      ansible.builtin.copy:
        src: bashrc-root
        dest: /root/.bashrc
        owner: root
        group: root
        mode: 0644

    - name: Configure Bash shell for future users
      ansible.builtin.copy:
        src: bashrc-user
        dest: /etc/skel/.bashrc
        owner: root
        group: root
        mode: 0644

    - name: Install Vim
      ansible.builtin.dnf:
        name: vim-enhanced
        state: present
        install_weak_deps: false

    - name: Configure Vim editor for root
      ansible.builtin.copy:
        src: vimrc
        dest: /root/.vimrc
        owner: root
        group: root
        mode: 0644

    - name: Configure Vim editor for future users
      ansible.builtin.copy:
        src: vimrc
        dest: /etc/skel/.vimrc
        owner: root
        group: root
        mode: 0644

# Dépôts officiels

# Dépôts EPEL

# Dépôts ELRepo

# Dépôts RPMFusion

# Installer le groupe de paquets Base

# Installer quelques outils supplémentaires

# Installer X11 + polices de base

# Installer KDE de base

# Installer GDM pour KDE

# Installer une panoplie d'applications

  handlers:

    - name: Relabel filesystem
      ansible.builtin.file:
        path: /.autorelabel
        state: touch

...
