#!/usr/bin/ansible-playbook --inventory=localhost,
#
# install.yml
---
- hosts: localhost
  connection: local
  force_handlers: true

  tasks:

    - name: Enable SELinux in enforcing mode
      ansible.posix.selinux:
        policy: targeted
        state: enforcing
      notify: Relabel filesystem

    - name: Configure Bash shell for root
      ansible.builtin.copy:
        src: bashrc-root
        dest: /root/.bashrc
        owner: root
        group: root
        mode: 0644

    - name: Configure Bash shell for future users
      ansible.builtin.copy:
        src: bashrc-user
        dest: /etc/skel/.bashrc
        owner: root
        group: root
        mode: 0644

    - name: Install Vim
      ansible.builtin.dnf:
        name: vim-enhanced
        state: present
        install_weak_deps: false

    - name: Configure Vim editor for root
      ansible.builtin.copy:
        src: vimrc
        dest: /root/.vimrc
        owner: root
        group: root
        mode: 0644

    - name: Configure Vim editor for future users
      ansible.builtin.copy:
        src: vimrc
        dest: /etc/skel/.vimrc
        owner: root
        group: root
        mode: 0644

    - name: Configure Rocky Linux BaseOS repository
      ansible.builtin.yum_repository:
        name: baseos
        file: rocky
        description: BaseOS
        baseurl: 
          - http://mirror.in2p3.fr/pub/linux/rocky/$releasever/BaseOS/$basearch/os/
          - http://dl.rockylinux.org/$contentdir/$releasever/BaseOS/$basearch/os/
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9
        enabled: true
        priority: 1

    - name: Configure Rocky Linux AppStream repository
      ansible.builtin.yum_repository:
        name: appstream
        file: rocky
        description: AppStream
        baseurl: 
          - http://mirror.in2p3.fr/pub/linux/rocky/$releasever/AppStream/$basearch/os/
          - http://dl.rockylinux.org/$contentdir/$releasever/AppStream/$basearch/os/
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9
        enabled: true
        priority: 1

    - name: Configure Rocky Linux CRB repository
      ansible.builtin.yum_repository:
        name: crb
        file: rocky
        description: CRB
        baseurl: 
          - http://mirror.in2p3.fr/pub/linux/rocky/$releasever/CRB/$basearch/os/
          - http://dl.rockylinux.org/$contentdir/$releasever/CRB/$basearch/os/
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9
        enabled: true
        priority: 1

    - name: Configure Rocky Linux Extras repository
      ansible.builtin.yum_repository:
        name: extras
        file: rocky-extras
        description: Extras
        baseurl: 
          - http://mirror.in2p3.fr/pub/linux/rocky/$releasever/extras/$basearch/os/
          - http://dl.rockylinux.org/$contentdir/$releasever/extras/$basearch/os/
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Rocky-9
        enabled: true
        priority: 1

    - name: Install EPEL release package
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: Configure EPEL repository
      ansible.builtin.yum_repository:
        name: epel
        file: epel
        description: EPEL
        baseurl: 
          - http://mirror.in2p3.fr/pub/linux/epel/$releasever/Everything/$basearch/
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-$releasever
        enabled: true
        priority: 10

    - name: Configure OpenH264 repository
      ansible.builtin.yum_repository:
        name: openh264
        file: epel-cisco-openh264
        description: OpenH264
        baseurl: 
          - https://codecs.fedoraproject.org/openh264/34/$basearch/os/
        gpgcheck: true
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-$releasever
        enabled: true
        priority: 10

    - name: Rename EPEL Cisco OpenH264 repository
      ansible.builtin.yum_repository:
        name: epel-cisco-openh264
        file: epel-cisco-openh264
        state: absent

    - name: Install ELRepo release package
      ansible.builtin.dnf:
        name: elrepo-release
        state: present

    - name: Configure ELRepo repository
      ansible.builtin.yum_repository:
        name: elrepo
        file: elrepo
        description: ELRepo
        baseurl: 
          - http://mirror.in2p3.fr/pub/linux/elrepo/elrepo/el9/$basearch/
          - http://elrepo.org/linux/elrepo/el9/$basearch/
        gpgcheck: true
        gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org file:///etc/pki/rpm-gpg/RPM-GPG-KEY-v2-elrepo.org"
        enabled: true
        priority: 10

    - name: Configure ELRepo Testing repository
      ansible.builtin.yum_repository:
        name: elrepo-testing
        file: elrepo
        description: ELRepo Testing
        baseurl: 
          - http://mirror.in2p3.fr/pub/linux/elrepo/testing/el9/$basearch/
          - http://elrepo.org/linux/testing/el9/$basearch/
        gpgcheck: true
        gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org file:///etc/pki/rpm-gpg/RPM-GPG-KEY-v2-elrepo.org"
        enabled: false
        priority: 10

    - name: Configure ELRepo Kernel repository
      ansible.builtin.yum_repository:
        name: elrepo-kernel
        file: elrepo
        description: ELRepo Kernel
        baseurl: 
          - http://mirror.in2p3.fr/pub/linux/elrepo/kernel/el9/$basearch/
          - http://elrepo.org/linux/kernel/el9/$basearch/
        gpgcheck: true
        gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org file:///etc/pki/rpm-gpg/RPM-GPG-KEY-v2-elrepo.org"
        enabled: false
        priority: 10

    - name: Configure ELRepo Extras repository
      ansible.builtin.yum_repository:
        name: elrepo-extras
        file: elrepo
        description: ELRepo Extras
        baseurl: 
          - http://mirror.in2p3.fr/pub/linux/elrepo/extras/el9/$basearch/
          - http://elrepo.org/linux/extras/el9/$basearch/
        gpgcheck: true
        gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-elrepo.org file:///etc/pki/rpm-gpg/RPM-GPG-KEY-v2-elrepo.org"
        enabled: false
        priority: 10

# Dépôts RPMFusion

# Installer le groupe de paquets Base

# Installer quelques outils supplémentaires

# Installer X11 + polices de base

# Installer KDE de base

# Installer GDM pour KDE

# Installer une panoplie d'applications

  handlers:

    - name: Relabel filesystem
      ansible.builtin.file:
        path: /.autorelabel
        state: touch

...
