---  # cron.yml

- name: Install ansible-pull cronjob
  cron:
    user: 'ansible'
    name: 'ansible provision'
    minute: '*/10'
    job: '/usr/bin/ansible-pull -o -U https://github.com/kikinovak/\
         ansible-demo.git > /dev/null'

...
