---  # gnome.yml

- name: Install python3-psutil package
  apt:
    name: python3-psutil

- name: Install Arc theme
  apt:
    name: arc-theme

- name: Set GTK theme
  dconf: 
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'Arc'"
  become_user: kikinovak

- name: Copy wallpaper file
  copy:
    src: files/wallpaper.jpg
    dest: /home/kikinovak/.wallpaper.jpg
    owner: kikinovak
    group: kikinovak
    mode: 0600

- name: Set GNOME wallpaper
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "''file:///home/kikinovak/.wallpaper.jpg'"
  become_user: kikinovak

...
